#外部配置加载顺序参考官方文档
#https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/htmlsingle/#boot-features-external-config
server:
  port: 4396
#配置文件注入
person:
  name: wcs${random.int} #随机数。。
  age: 24
  map: {k1: v1,k2: v2}
  list:
    - list1
    - list2
  dog:
    name: Huang
    age: 3
spring:
  profiles:
    active: dev #此时端口号为8081

---
#可以有多份配置，使用active激活对应配置
server:
     port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: prod